# Below is a list of extremely useful R packages.
install.packages("ggplot2")
install.packages("datasets")
install.packages("readxl") 
install.packages("dplyr")
install.packages("tidyr") 
install.packages("PerformanceAnalytics")
install.packages("corrplot") 
install.packages("gapminder")
install.packages("gridextra")
install.packages("Ecdat")
install.packages("corpcor")
install.packages("GPArotation")
install.packages("psych")
install.packages("IDPmisc")
install.packages("Lattice") 
install.packages("treetop")
install.packages("scales")
install.packages("rcompanion")
install.packages("gmodels")
install.packages("car")
install.packages("caret")
install.packages("gvlma")
install.packages("predictmeans")
install.packages("caret")
install.packages("magrittr")
install.packages("dplyr")
install.packages("tidyr")
install.packages("lmtest")
install.packages("popbio")
install.packages("e1071")
install.packages("data.table")
install.packages("aptest")
install.packages("ncvtest")
install.packages("effects")
install.packages("multcomp")
install.packages("mvnormtest")
install.packages("reshape2")
install.packages("DAAG")
install.packages("PeformanceAnalytics")
install.packages("corrplot")
install.packages("gapminder")
install.packages("gridExtra")
install.packages("purr")
install.packages("treemap")
install.packages("scales")
install.packages("vcd")
install.packages("Rserve")
install.packages("mvoutlier")
install.packages('Rcpp')


# To connect with Tableau, download and install Rserve.
install.packages("Rserve")
library(Rserve);Rserve()
library(mvoutlier)


# Linear Regression
install.packages("car")
install.packages("caret")
install.packages("gvlma")
install.packages("predictmeans")
install.packages("e1071")
install.packages("lmtest")
install.packages("magrittr")
install.packages("lmtest")
install.packages("gvlma")
install.packages("popbio")


# Factor Analysis
install.packages("corpcor")
install.packages("GPArotation")
install.packages("psych")
install.packages("IDPmisc)

# Data Transformation
install.packages("rcompanion")

